project:
  type: website
  output-dir: docs

website:
  title: "Python Programming"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: a.html
        text: Online Interpreter

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



